# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20160306_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
    ]
