# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=product.models.upload_location),
        ),
    ]
